name: recommender-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - streamlit==1.33.0
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.4.2
      - scipy==1.12.0
